import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // article用のサイドバー
  articlesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'articles', // Generate sidebar slice from the docs/articles folder
    }],
　// 用語集用のサイドバー
  wordsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'words', // Generate sidebar slice from the docs/words folder
    }],
};

export default sidebars;
